#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable anchor.service >/dev/null 2>&1 || true

    if [ -f /etc/anchor/anchor.toml ]; then
        systemctl restart anchor.service
    fi
fi

